FROM vllm/vllm-openai:latest

COPY . /atra-server                                                            
WORKDIR /atra-server

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["/bin/bash"]

CMD [ "run_vllm.sh" ]
