FROM vllm/vllm-openai:v0.4.0.post1

COPY . /atra-server                                                            
WORKDIR /atra-server

RUN chmod +x ./entrypoint.sh

ENTRYPOINT ["/bin/bash"]

CMD [ "run_vllm.sh" ]
