# Define default values
DEFAULT_DATASET_NAME="flozi00/german-canary-asr-0324"
DEFAULT_MODEL_NAME_OR_PATH="facebook/w2v-bert-2.0"
DEFAULT_DATASET_CONFIG_NAME="default"
DEFAULT_OUTPUT_DIR="./wav2vec2-large-xlsr-53-german-canary"
DEFAULT_NUM_TRAIN_EPOCHS="1"
DEFAULT_PER_DEVICE_TRAIN_BATCH_SIZE="4"
DEFAULT_GRADIENT_ACCUMULATION_STEPS="8"
DEFAULT_LEARNING_RATE="3e-4"
DEFAULT_WARMUP_STEPS="500"
DEFAULT_TEXT_COLUMN_NAME="transkription"
DEFAULT_AUDIO_COLUMN_NAME="audio"
DEFAULT_LENGTH_COLUMN_NAME="input_length"
DEFAULT_SAVE_STEPS="400"
DEFAULT_EVAL_STEPS="100"
DEFAULT_LAYERDROP="0.0"
DEFAULT_SAVE_TOTAL_LIMIT="3"
DEFAULT_OPTIMIZER="paged_adamw_8bit"

# Check for environment variables and use them if they exist
DATASET_NAME=${DATASET_NAME:-$DEFAULT_DATASET_NAME}
MODEL_NAME_OR_PATH=${MODEL_NAME_OR_PATH:-$DEFAULT_MODEL_NAME_OR_PATH}
DATASET_CONFIG_NAME=${DATASET_CONFIG_NAME:-$DEFAULT_DATASET_CONFIG_NAME}
OUTPUT_DIR=${OUTPUT_DIR:-$DEFAULT_OUTPUT_DIR}
NUM_TRAIN_EPOCHS=${NUM_TRAIN_EPOCHS:-$DEFAULT_NUM_TRAIN_EPOCHS}
PER_DEVICE_TRAIN_BATCH_SIZE=${PER_DEVICE_TRAIN_BATCH_SIZE:-$DEFAULT_PER_DEVICE_TRAIN_BATCH_SIZE}
GRADIENT_ACCUMULATION_STEPS=${GRADIENT_ACCUMULATION_STEPS:-$DEFAULT_GRADIENT_ACCUMULATION_STEPS}
LEARNING_RATE=${LEARNING_RATE:-$DEFAULT_LEARNING_RATE}
WARMUP_STEPS=${WARMUP_STEPS:-$DEFAULT_WARMUP_STEPS}
TEXT_COLUMN_NAME=${TEXT_COLUMN_NAME:-$DEFAULT_TEXT_COLUMN_NAME}
AUDIO_COLUMN_NAME=${AUDIO_COLUMN_NAME:-$DEFAULT_AUDIO_COLUMN_NAME}
LENGTH_COLUMN_NAME=${LENGTH_COLUMN_NAME:-$DEFAULT_LENGTH_COLUMN_NAME}
SAVE_STEPS=${SAVE_STEPS:-$DEFAULT_SAVE_STEPS}
EVAL_STEPS=${EVAL_STEPS:-$DEFAULT_EVAL_STEPS}
LAYERDROP=${LAYERDROP:-$DEFAULT_LAYERDROP}
SAVE_TOTAL_LIMIT=${SAVE_TOTAL_LIMIT:-$DEFAULT_SAVE_TOTAL_LIMIT}
OPTIMIZER=${OPTIMIZER:-$DEFAULT_OPTIMIZER}

# Construct the command string
CMD="python3 train_speech_recognition_ctc.py --dataset_name=\"$DATASET_NAME\" \
--model_name_or_path=\"$MODEL_NAME_OR_PATH\" \
--dataset_config_name=\"$DATASET_CONFIG_NAME\" \
--output_dir=\"$OUTPUT_DIR\" \
--overwrite_output_dir \
--num_train_epochs=\"$NUM_TRAIN_EPOCHS\" \
--per_device_train_batch_size=\"$PER_DEVICE_TRAIN_BATCH_SIZE\" \
--gradient_accumulation_steps=\"$GRADIENT_ACCUMULATION_STEPS\" \
--learning_rate=\"$LEARNING_RATE\" \
--warmup_steps=\"$WARMUP_STEPS\" \
--evaluation_strategy=\"steps\" \
--text_column_name=\"$TEXT_COLUMN_NAME\" \
--audio_column_name=\"$AUDIO_COLUMN_NAME\" \
--length_column_name=\"$LENGTH_COLUMN_NAME\" \
--save_steps=\"$SAVE_STEPS\" \
--eval_steps=\"$EVAL_STEPS\" \
--layerdrop=\"$LAYERDROP\" \
--save_total_limit=\"$SAVE_TOTAL_LIMIT\" \
--gradient_checkpointing \
--optim=\"$OPTIMIZER\" \
--fp16 \
--group_by_length \
--push_to_hub \
--do_train --do_eval"

# Run the command
eval $CMD